### PR TITLE
Update accuracy formals for upcoming forecast package release

### PR DESCRIPTION
**Pull request by mitchelloharawild**
For better consistency with the signature of `fabletools::accuracy()` and other generics, the `forecast::accuracy()` generic will be updated in the next release (https://github.com/robjhyndman/forecast/commit/6b9ab090cd01062460c285d17dd6bc6d6d310a48).

This PR updates accuracy methods to use this updated generic signature.

### CODE REVIEW

**Comment by mitchelloharawild** [comment]
Changes to the forecast package in the next version will cause check issues
with packages that define methods for accuracy(). There is no time pressure
on releasing this version of forecast, but I do think that packages should
be submitted at similar times.

**Comment by dashaub** [comment]
Right, so if I didn't upload a new CRAN version of "forecastHybrid", wouldn't that block your release of "forecast"? But I can't make a new release yet since this change requires a version of "forecast" that does not exist; we have a circular dependency problem.

At least this is what I've experienced in the past when releasing a CRAN package where the new version breaks a dependency package; they generally block the release until the dependency package is working too.

If this is the case we might want to do it in this order:
1. Make this change, but without the the version bump requirement of "forecast" 8.12
2. Assuming "forecastHybrid" still builds fine (not sure, since right now CI fails on installing the nonexistent "forecast" 8.12), make a CRAN "forecastHybrid" release.
3. The "forecast" package is now unblocked. Make any new releases at your leisure.

**Comment by mitchelloharawild** [comment]
I've been having some luck with CRAN lately using simultaneous releases,
mentioning the simultaneity in the cran-comments.

But yes, it will block forecast and have a circular dependency. I can set a
remotes field for dev forecast if you'd like to test changes using your CI.

**Comment by mitchelloharawild** [comment]
We're preparing a minor release of forecast within the next week which will include the changes to `accuracy()` formals. Is it possible to also release a patch for forecastHybrid to go along with this submission?

**Comment by dashaub** [comment]
@mitchelloharawild Yes, I'll be ready to push a new version right after the new "forecast" goes up.

**Comment by mitchelloharawild** [comment]
Great, thanks. I'll let you know when forecast is submitted to CRAN.

**Comment by mitchelloharawild** [comment]
@dashaub `forecast` has been submitted to CRAN and passed automatic checks.

**Pull request merged**
